# .github/workflows/go.yml
name: Go Build & Test Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code using the latest version of actions/checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup the Go environment with Go version 1.23 using the latest version of actions/setup-go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'
          cache-dependency-path: go.sum

      # Download project dependencies
      - name: Download dependencies
        run: go mod download

      # Create .env file from secret
      - name: Create .env file
        run: echo "${{ secrets.ENV_TEST_FILE }}" > .env

      # Run tests using Makefile
      - name: Run tests using Makefile
        run: make test
        id: tests
